### ISSUE TITLE
Feature: Explore Fediverse

### ISSUE THREAD

**Issue by AmarOk1412** [AmarOk1412/Cha-Cuit#10]
# TODO list:

+ [x] Make @chef@cha-cu.it discoverable
+ [x] View articles from mastodon
+ [x] Show likes
+ [x] Show boost
+ [x] Receive new recipes from the fediverse
+ [x] Block list
+ [x] Doc (block, mentions)

For inbox:

+ [x] Decide for incoming format for mastodon
+ [x] Follow from file
+ [x] Add config to follow back
+ [x] Add follow instance
+ [x] Update follows on cache update
+ [x] Verify signatures
+ [ ] Close missing TODOs
+ [x] Save mentions

**Comment by AmarOk1412** [comment]
https://git.jlel.se/jlelse/hugo-activitystreams/src/branch/master/layouts/_default
